### ISSUE TITLE
We should add it to go-web-framework-benchmark even just for advertising

### ISSUE THREAD

**Issue by frederikhors** [vmihailenco/treemux#2]
We should add it to [go-web-framework-benchmark](https://github.com/smallnest/go-web-framework-benchmark) even just for advertising.

**Comment by vmihailenco** [comment]
Sounds good. Do you want to give it a try?

**Comment by frederikhors** [comment]
Yeah I will in the next few hours.

**Comment by frederikhors** [comment]
Added here: https://github.com/smallnest/go-web-framework-benchmark/pull/112.

We can close this if you find it correct, @vmihailenco or maybe we can wait for it to be merged.
